### PR TITLE
Update build.md

### PR DESCRIPTION
**Pull request by bmsleight**
Missing a mkdir $HOME/bin

### CODE REVIEW

**Comment by scottlamb** [comment]
If `$HOME/bin` doesn't exist, it's also probably not in `$PATH`, so the `nvr init` command a couple lines down will fail.

This doc is supposed to be aimed at pretty savvy folks and says "This document doesn't spell out as many details as the installation instructions." So I don't want it to go on a long tangent about how to set up your `$PATH` in all the various shells folks might use. Still, maybe it's worth adding one sentence reminding to check `$PATH` if that command fails, even linking to a guide if you can find a good one. What do you think?

**Comment by bmsleight** [comment]
Good idea.

I am pulling my notes together on a build from source on a PI 3 - I can do
a separate page on the wiki which could be used as a reference ?
This could have more detail such as check check $PATH.

**Comment by scottlamb** [comment]
A reference on the wiki sounds great!

**Comment by bmsleight** [comment]
Superseded by https://github.com/scottlamb/moonfire-nvr/pull/190

**Pull request closed without merging**
